#!/bin/bash
#
# ZNC Installer
#
# Originally written for QuickBox.io by liara
#
# QuickBox Copyright (C) 2017 QuickBox.io
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.


user=$(cut -d: -f1 < /root/.master.info)
passwd=$(cut -d: -f2 < /root/.master.info)
salt=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 ; echo '')
shapass=$(echo -n $passwd$salt | sha256sum | awk '{print $1}')
port=$(cat /home/seedit4me/.znc_port)

DISTRO=$(lsb_release -is)
CODENAME=$(lsb_release -cs)
#if [[ -f /install/.tools.lock ]]; then
#  log="/srv/tools/logs/output.log"
#else
#  log="/dev/null"
#fi

echo "Installing ZNC. Please wait ... " >> ${SEEDIT_LOG} 2>&1
echo "" >> ${SEEDIT_LOG} 2>&1
echo "" >> ${SEEDIT_LOG} 2>&1
useradd znc -m -s /bin/bash
passwd znc -l >> ${SEEDIT_LOG} 2>&1

if [[ $CODENAME == jessie ]]; then
  if [[ -z $(cat /etc/apt/sources.list | grep backports) ]]; then
    echo "deb http://deb.debian.org/debian jessie-backports main contrib non-free" >> /etc/apt/sources.list
  fi
  cat > /etc/apt/preferences.d/znc <<ZNCP
Package: *znc*
Pin: release a=jessie-backports
Pin-Priority: 500
ZNCP
  #echo "deb http://packages.temporal-intelligence.net/znc/debian/ ${CODENAME} main" > /etc/apt/sources.list.d/znc.list
  #echo "#deb-src http://packages.temporal-intelligence.net/znc/debian/ ${CODENAME} main" >> /etc/apt/sources.list.d/znc.list
  #wget --quiet http://packages.temporal-intelligence.net/repo.gpg.key -O - | apt-key add - > /dev/null 2>&1
#elif [[ $DISTRO == Ubuntu ]]; then
  #sudo apt-get install -q -y software-properties-common > /dev/null 2>&1
  #sudo add-apt-repository -q -y ppa:teward/znc > /dev/null 2>&1
fi
  apt-get update -q -y > /dev/null 2>&1
  apt-get install znc -q -y > /dev/null 2>&1
  #sudo -u znc crontab -l | echo -e "*/10 * * * * /usr/bin/znc >/dev/null 2>&1\n@reboot /usr/bin/znc >/dev/null 2>&1" | crontab -u znc - > /dev/null 2>&1
  cat > /etc/systemd/system/znc.service <<ZNC
[Unit]
Description=ZNC, an advanced IRC bouncer
After=network-online.target
     
[Service]
ExecStart=/usr/bin/znc -f
User=znc
Restart=always
     
[Install]
WantedBy=multi-user.target
ZNC

  mkdir /home/znc/.znc
  mkdir /home/znc/.znc/configs

  cat > /home/znc/.znc/configs/znc.conf <<ZNCONF
// WARNING
//
// Do NOT edit this file while ZNC is running!
// Use webadmin or *controlpanel instead.
//
// Altering this file by hand will forfeit all support.
//
// But if you feel risky, you might want to read help on /znc saveconfig and /znc rehash.
// Also check http://en.znc.in/wiki/Configuration

Version = 1.6.3
<Listener l>
        Port = $port
        IPv4 = true
        IPv6 = false
        SSL = false
</Listener>
LoadModule = webadmin

<User seedit4me>
		<Pass password>
		        Method = sha256
		        Hash = ${shapass}
		        Salt = ${salt}
		</Pass>
//        Pass       = sha256#${shapass}#${salt}#
        Admin      = ${user}
        Nick       = ${user}
        AltNick    = ${user}_
        Ident      = ${user}
        RealName   = Got ZNC?
        LoadModule = chansaver
        LoadModule = controlpanel
</User>
ZNCONF

chown -R znc:znc /home/znc/.znc/configs
chmod -R 777 /home/znc/.znc/configs


systemctl enable znc
  # echo "#### ZNC configuration will now run. Please answer the following prompts ####"
  sleep 5
  # sudo -H -u znc znc --makeconf
  killall -u znc znc > /dev/null 2>&1
  sleep 1
  if [[ -f /install/.panel.lock ]]; then
    echo "$(grep Port /home/znc/.znc/configs/znc.conf | sed -e 's/^[ \t]*//')" > /srv/panel/db/znc.txt
    echo "$(grep SSL /home/znc/.znc/configs/znc.conf | sed -e 's/^[ \t]*//')" >> /srv/panel/db/znc.txt
  fi
  # Check for LE cert, and copy it if available.
#  chkhost="$(find /etc/nginx/ssl/* -maxdepth 1 -type d | cut -f 5 -d '/')"
#  if [[ -n $chkhost ]]; then
#    defaulthost=$(grep -m1 "server_name" /etc/nginx/sites-enabled/default | awk '{print $2}' | sed 's/;//g')
#    cat /etc/nginx/ssl/"$defaulthost"/{key,fullchain}.pem > /home/znc/.znc/znc.pem
#    crontab -l > newcron.txt | sed -i  "s#cron#cron --post-hook \"cat /etc/nginx/ssl/"$defaulthost"/{key,fullchain}.pem > /home/znc/.znc/znc.pem\"#g" newcron.txt | crontab newcron.txt | rm newcron.txt
#  fi
  systemctl start znc
  touch /install/.znc.lock
echo "#### ZNC now installed! ####"
