#!/bin/bash
IFACE=$(/usr/bin/sudo ip route | grep default | sed -e "s/^.*dev.//" -e "s/.proto.*//" | awk '{print $1}')
function _tc() {
    vnstat -u
    TOTALSTX=$(vnstat --dumpdb -i $IFACE | grep 'totaltx;' | cut -d';' -f2)
    TTX=0
    LIMIT=0
    for TOTALTX in $TOTALSTX; do (('TTX += TOTALTX')); done;

    HOSTNAME=$(hostname -s)
    VMID=${HOSTNAME//ct/}
    TIME=$(date +%s);
    URL="https://my.dev.seedit4.me/api/vmtinfo/${VMID}/${TTX}/${TIME}"

    echo 'IFACE' $IFACE
    echo 'TTX' $TTX
    echo 'VMID' $VMID
    echo 'URL' $URL

    LIMIT=$(curl -s -w "\n%{http_code}" "${URL}" | {
        read -r body
        echo $body
    })

    echo 'LIMIT' $LIMIT

    if [ $LIMIT == 'true' ]; then
        #echo -e "\n clearing conf ------------------------------------------------\n"
        sudo /etc/swizzin/scripts/tools/ws -c -a $IFACE
        #echo -e "\n setting up ---------------------------------------------------\n"
        sudo /etc/swizzin/scripts/tools/ws -a $IFACE -u 100000
        #echo -e "\n info ---------------------------------------------------------\n"
        sudo /etc/swizzin/scripts/tools/ws -s -a $IFACE
    fi

    if [ $LIMIT == 'false' ]; then
        sudo /etc/swizzin/scripts/tools/ws -c -a $IFACE
    fi
    exit 0
}
_tc
