#!/bin/bash

IFACE="venet0"

function _tc() {
  vnstat -u
  TOTALSRX=`vnstat --dumpdb -i $IFACE | grep 'totalrx;' | cut -d';' -f2`
  TOTALSTX=`vnstat --dumpdb -i $IFACE | grep 'totaltx;' | cut -d';' -f2`

  TOTALSRXMB=0
  TOTALSTXMB=0
  DL=0
  UL=0
  LIMIT=0

  for TOTALRX in $TOTALSRX
  do
    let 'TOTALSRXMB += TOTALRX'
  done

  for TOTALTX in $TOTALSTX
  do
    let 'TOTALSTXMB += TOTALTX'
  done

  DL=$(($TOTALSRXMB * 1024))
  UL=$(($TOTALSTXMB * 1024))

  HOSTNAME=$(hostname -s)
  VMID=${HOSTNAME//ct/}

  URL="https://my.dev.seedit4.me/api/vmtinfo/${VMID}/${UL}"

  LIMIT=$(curl -s -w "\n%{http_code}" "${URL}" | {
    read body
    echo $body
  })

  if [ LIMIT == 'true' ]; then
    sudo /etc/swizzin/scripts/tools/ws -c -a venet0
    sudo /etc/swizzin/scripts/tools/ws -a venet0 -u 100000
    sudo /etc/swizzin/scripts/tools/ws -s -a venet0
  fi

  if [ LIMIT == 'false' ]; then
    sudo /etc/swizzin/scripts/tools/ws -c -a venet0
  fi

  exit 0
}

_tc
