#!/bin/bash

function install_fpm() {
    /usr/local/bin/fpm -h > /dev/null 2>&1
    ln -s /usr/local/bin/fpm /bin/fp
    exit=$?
    if [[ ! $exit == '0' ]]; then
        apt_install ruby ruby-dev libffi-dev
        echo_progress_start "Installing fpm through ruby/gem"
        gem install fpm >> $log 2>&1
        echo_progress_done
    fi
}
