#!/bin/bash

function install_fpm() {
    fpm -h > /dev/null 2>&1
    exit=$?
    if [[ ! $exit == '0' ]]; then
        apt_install ruby ruby-dev libffi-dev
        echo_progress_start "Installing fpm through ruby/gem"
        gem install fpm >> $log 2>&1
        ln -s /usr/local/bin/fpm /bin/fpm
        echo_progress_done
    fi
}
