#!/bin/bash

function install_fpm () {
  /usr/local/bin/fpm -h > /dev/null 2>&1
  exit=$?
  if [[ ! $exit == '0' ]]; then
    echo "Installing fpm package management with ruby/gem"
    apt_install ruby ruby-dev
    gem install fpm > /dev/null 2>&1
  fi
}